// code generated by `go run partial_gen.go`; DO NOT EDIT.

package funcs

type Func2[T1, T2, R any] func(T1, T2) R

func Of2[
	T1, T2, R any,
	F ~func(T1, T2) R,
](fn F) Func2[T1, T2, R] {
	return Func2[T1, T2, R](fn)
}

func (fn Func2[T1, T2, R]) Call(t1 T1, t2 T2) R {
	return fn(t1, t2)
}

func (fn Func2[T1, T2, R]) Partial(t1 T1) Func1[T2, R] {
	return Partial2(fn, t1)
}

func (fn Func2[T1, T2, R]) Partial1(t1 T1) Func1[T2, R] {
	return Partial2N1(fn, t1)
}

func (fn Func2[T1, T2, R]) Partial2(t2 T2) Func1[T1, R] {
	return Partial2N2(fn, t2)
}

func (fn Func2[T1, T2, R]) PartialR(t2 T2) Func1[T1, R] {
	return Partial2R(fn, t2)
}

func Partial2[
	T1, T2, R any,
	F ~func(T1, T2) R,
](fn F, t1 T1) Func1[T2, R] {
	return func(t2 T2) R {
		return fn(t1, t2)
	}
}

func Partial2N1[
	T1, T2, R any,
	F ~func(T1, T2) R,
](fn F, t1 T1) Func1[T2, R] {
	return func(t2 T2) R {
		return fn(t1, t2)
	}
}

func Partial2N2[
	T1, T2, R any,
	F ~func(T1, T2) R,
](fn F, t2 T2) Func1[T1, R] {
	return func(t1 T1) R {
		return fn(t1, t2)
	}
}

func Partial2R[
	T1, T2, R any,
	F ~func(T1, T2) R,
](fn F, t2 T2) Func1[T1, R] {
	return func(t1 T1) R {
		return fn(t1, t2)
	}
}

type Func3[T1, T2, T3, R any] func(T1, T2, T3) R

func Of3[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F) Func3[T1, T2, T3, R] {
	return Func3[T1, T2, T3, R](fn)
}

func (fn Func3[T1, T2, T3, R]) Call(t1 T1, t2 T2, t3 T3) R {
	return fn(t1, t2, t3)
}

func (fn Func3[T1, T2, T3, R]) Partial(t1 T1) Func2[T2, T3, R] {
	return Partial3(fn, t1)
}

func (fn Func3[T1, T2, T3, R]) Partial1(t1 T1) Func2[T2, T3, R] {
	return Partial3N1(fn, t1)
}

func (fn Func3[T1, T2, T3, R]) Partial2(t2 T2) Func2[T1, T3, R] {
	return Partial3N2(fn, t2)
}

func (fn Func3[T1, T2, T3, R]) Partial3(t3 T3) Func2[T1, T2, R] {
	return Partial3N3(fn, t3)
}

func (fn Func3[T1, T2, T3, R]) PartialR(t3 T3) Func2[T1, T2, R] {
	return Partial3R(fn, t3)
}

func Partial3[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F, t1 T1) Func2[T2, T3, R] {
	return func(t2 T2, t3 T3) R {
		return fn(t1, t2, t3)
	}
}

func Partial3N1[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F, t1 T1) Func2[T2, T3, R] {
	return func(t2 T2, t3 T3) R {
		return fn(t1, t2, t3)
	}
}

func Partial3N2[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F, t2 T2) Func2[T1, T3, R] {
	return func(t1 T1, t3 T3) R {
		return fn(t1, t2, t3)
	}
}

func Partial3N3[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F, t3 T3) Func2[T1, T2, R] {
	return func(t1 T1, t2 T2) R {
		return fn(t1, t2, t3)
	}
}

func Partial3R[
	T1, T2, T3, R any,
	F ~func(T1, T2, T3) R,
](fn F, t3 T3) Func2[T1, T2, R] {
	return func(t1 T1, t2 T2) R {
		return fn(t1, t2, t3)
	}
}

type Func4[T1, T2, T3, T4, R any] func(T1, T2, T3, T4) R

func Of4[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F) Func4[T1, T2, T3, T4, R] {
	return Func4[T1, T2, T3, T4, R](fn)
}

func (fn Func4[T1, T2, T3, T4, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4) R {
	return fn(t1, t2, t3, t4)
}

func (fn Func4[T1, T2, T3, T4, R]) Partial(t1 T1) Func3[T2, T3, T4, R] {
	return Partial4(fn, t1)
}

func (fn Func4[T1, T2, T3, T4, R]) Partial1(t1 T1) Func3[T2, T3, T4, R] {
	return Partial4N1(fn, t1)
}

func (fn Func4[T1, T2, T3, T4, R]) Partial2(t2 T2) Func3[T1, T3, T4, R] {
	return Partial4N2(fn, t2)
}

func (fn Func4[T1, T2, T3, T4, R]) Partial3(t3 T3) Func3[T1, T2, T4, R] {
	return Partial4N3(fn, t3)
}

func (fn Func4[T1, T2, T3, T4, R]) Partial4(t4 T4) Func3[T1, T2, T3, R] {
	return Partial4N4(fn, t4)
}

func (fn Func4[T1, T2, T3, T4, R]) PartialR(t4 T4) Func3[T1, T2, T3, R] {
	return Partial4R(fn, t4)
}

func Partial4[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t1 T1) Func3[T2, T3, T4, R] {
	return func(t2 T2, t3 T3, t4 T4) R {
		return fn(t1, t2, t3, t4)
	}
}

func Partial4N1[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t1 T1) Func3[T2, T3, T4, R] {
	return func(t2 T2, t3 T3, t4 T4) R {
		return fn(t1, t2, t3, t4)
	}
}

func Partial4N2[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t2 T2) Func3[T1, T3, T4, R] {
	return func(t1 T1, t3 T3, t4 T4) R {
		return fn(t1, t2, t3, t4)
	}
}

func Partial4N3[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t3 T3) Func3[T1, T2, T4, R] {
	return func(t1 T1, t2 T2, t4 T4) R {
		return fn(t1, t2, t3, t4)
	}
}

func Partial4N4[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t4 T4) Func3[T1, T2, T3, R] {
	return func(t1 T1, t2 T2, t3 T3) R {
		return fn(t1, t2, t3, t4)
	}
}

func Partial4R[
	T1, T2, T3, T4, R any,
	F ~func(T1, T2, T3, T4) R,
](fn F, t4 T4) Func3[T1, T2, T3, R] {
	return func(t1 T1, t2 T2, t3 T3) R {
		return fn(t1, t2, t3, t4)
	}
}

type Func5[T1, T2, T3, T4, T5, R any] func(T1, T2, T3, T4, T5) R

func Of5[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F) Func5[T1, T2, T3, T4, T5, R] {
	return Func5[T1, T2, T3, T4, T5, R](fn)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5) R {
	return fn(t1, t2, t3, t4, t5)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial(t1 T1) Func4[T2, T3, T4, T5, R] {
	return Partial5(fn, t1)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial1(t1 T1) Func4[T2, T3, T4, T5, R] {
	return Partial5N1(fn, t1)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial2(t2 T2) Func4[T1, T3, T4, T5, R] {
	return Partial5N2(fn, t2)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial3(t3 T3) Func4[T1, T2, T4, T5, R] {
	return Partial5N3(fn, t3)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial4(t4 T4) Func4[T1, T2, T3, T5, R] {
	return Partial5N4(fn, t4)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) Partial5(t5 T5) Func4[T1, T2, T3, T4, R] {
	return Partial5N5(fn, t5)
}

func (fn Func5[T1, T2, T3, T4, T5, R]) PartialR(t5 T5) Func4[T1, T2, T3, T4, R] {
	return Partial5R(fn, t5)
}

func Partial5[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t1 T1) Func4[T2, T3, T4, T5, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5N1[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t1 T1) Func4[T2, T3, T4, T5, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5N2[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t2 T2) Func4[T1, T3, T4, T5, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5N3[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t3 T3) Func4[T1, T2, T4, T5, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5N4[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t4 T4) Func4[T1, T2, T3, T5, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5N5[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t5 T5) Func4[T1, T2, T3, T4, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

func Partial5R[
	T1, T2, T3, T4, T5, R any,
	F ~func(T1, T2, T3, T4, T5) R,
](fn F, t5 T5) Func4[T1, T2, T3, T4, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4) R {
		return fn(t1, t2, t3, t4, t5)
	}
}

type Func6[T1, T2, T3, T4, T5, T6, R any] func(T1, T2, T3, T4, T5, T6) R

func Of6[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F) Func6[T1, T2, T3, T4, T5, T6, R] {
	return Func6[T1, T2, T3, T4, T5, T6, R](fn)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6) R {
	return fn(t1, t2, t3, t4, t5, t6)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial(t1 T1) Func5[T2, T3, T4, T5, T6, R] {
	return Partial6(fn, t1)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial1(t1 T1) Func5[T2, T3, T4, T5, T6, R] {
	return Partial6N1(fn, t1)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial2(t2 T2) Func5[T1, T3, T4, T5, T6, R] {
	return Partial6N2(fn, t2)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial3(t3 T3) Func5[T1, T2, T4, T5, T6, R] {
	return Partial6N3(fn, t3)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial4(t4 T4) Func5[T1, T2, T3, T5, T6, R] {
	return Partial6N4(fn, t4)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial5(t5 T5) Func5[T1, T2, T3, T4, T6, R] {
	return Partial6N5(fn, t5)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) Partial6(t6 T6) Func5[T1, T2, T3, T4, T5, R] {
	return Partial6N6(fn, t6)
}

func (fn Func6[T1, T2, T3, T4, T5, T6, R]) PartialR(t6 T6) Func5[T1, T2, T3, T4, T5, R] {
	return Partial6R(fn, t6)
}

func Partial6[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t1 T1) Func5[T2, T3, T4, T5, T6, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N1[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t1 T1) Func5[T2, T3, T4, T5, T6, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N2[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t2 T2) Func5[T1, T3, T4, T5, T6, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N3[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t3 T3) Func5[T1, T2, T4, T5, T6, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N4[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t4 T4) Func5[T1, T2, T3, T5, T6, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N5[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t5 T5) Func5[T1, T2, T3, T4, T6, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6N6[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t6 T6) Func5[T1, T2, T3, T4, T5, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

func Partial6R[
	T1, T2, T3, T4, T5, T6, R any,
	F ~func(T1, T2, T3, T4, T5, T6) R,
](fn F, t6 T6) Func5[T1, T2, T3, T4, T5, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5) R {
		return fn(t1, t2, t3, t4, t5, t6)
	}
}

type Func7[T1, T2, T3, T4, T5, T6, T7, R any] func(T1, T2, T3, T4, T5, T6, T7) R

func Of7[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F) Func7[T1, T2, T3, T4, T5, T6, T7, R] {
	return Func7[T1, T2, T3, T4, T5, T6, T7, R](fn)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
	return fn(t1, t2, t3, t4, t5, t6, t7)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial(t1 T1) Func6[T2, T3, T4, T5, T6, T7, R] {
	return Partial7(fn, t1)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial1(t1 T1) Func6[T2, T3, T4, T5, T6, T7, R] {
	return Partial7N1(fn, t1)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial2(t2 T2) Func6[T1, T3, T4, T5, T6, T7, R] {
	return Partial7N2(fn, t2)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial3(t3 T3) Func6[T1, T2, T4, T5, T6, T7, R] {
	return Partial7N3(fn, t3)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial4(t4 T4) Func6[T1, T2, T3, T5, T6, T7, R] {
	return Partial7N4(fn, t4)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial5(t5 T5) Func6[T1, T2, T3, T4, T6, T7, R] {
	return Partial7N5(fn, t5)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial6(t6 T6) Func6[T1, T2, T3, T4, T5, T7, R] {
	return Partial7N6(fn, t6)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) Partial7(t7 T7) Func6[T1, T2, T3, T4, T5, T6, R] {
	return Partial7N7(fn, t7)
}

func (fn Func7[T1, T2, T3, T4, T5, T6, T7, R]) PartialR(t7 T7) Func6[T1, T2, T3, T4, T5, T6, R] {
	return Partial7R(fn, t7)
}

func Partial7[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t1 T1) Func6[T2, T3, T4, T5, T6, T7, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N1[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t1 T1) Func6[T2, T3, T4, T5, T6, T7, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N2[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t2 T2) Func6[T1, T3, T4, T5, T6, T7, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N3[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t3 T3) Func6[T1, T2, T4, T5, T6, T7, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N4[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t4 T4) Func6[T1, T2, T3, T5, T6, T7, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N5[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t5 T5) Func6[T1, T2, T3, T4, T6, T7, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N6[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t6 T6) Func6[T1, T2, T3, T4, T5, T7, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7N7[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t7 T7) Func6[T1, T2, T3, T4, T5, T6, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

func Partial7R[
	T1, T2, T3, T4, T5, T6, T7, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7) R,
](fn F, t7 T7) Func6[T1, T2, T3, T4, T5, T6, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6) R {
		return fn(t1, t2, t3, t4, t5, t6, t7)
	}
}

type Func8[T1, T2, T3, T4, T5, T6, T7, T8, R any] func(T1, T2, T3, T4, T5, T6, T7, T8) R

func Of8[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F) Func8[T1, T2, T3, T4, T5, T6, T7, T8, R] {
	return Func8[T1, T2, T3, T4, T5, T6, T7, T8, R](fn)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
	return fn(t1, t2, t3, t4, t5, t6, t7, t8)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial(t1 T1) Func7[T2, T3, T4, T5, T6, T7, T8, R] {
	return Partial8(fn, t1)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial1(t1 T1) Func7[T2, T3, T4, T5, T6, T7, T8, R] {
	return Partial8N1(fn, t1)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial2(t2 T2) Func7[T1, T3, T4, T5, T6, T7, T8, R] {
	return Partial8N2(fn, t2)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial3(t3 T3) Func7[T1, T2, T4, T5, T6, T7, T8, R] {
	return Partial8N3(fn, t3)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial4(t4 T4) Func7[T1, T2, T3, T5, T6, T7, T8, R] {
	return Partial8N4(fn, t4)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial5(t5 T5) Func7[T1, T2, T3, T4, T6, T7, T8, R] {
	return Partial8N5(fn, t5)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial6(t6 T6) Func7[T1, T2, T3, T4, T5, T7, T8, R] {
	return Partial8N6(fn, t6)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial7(t7 T7) Func7[T1, T2, T3, T4, T5, T6, T8, R] {
	return Partial8N7(fn, t7)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) Partial8(t8 T8) Func7[T1, T2, T3, T4, T5, T6, T7, R] {
	return Partial8N8(fn, t8)
}

func (fn Func8[T1, T2, T3, T4, T5, T6, T7, T8, R]) PartialR(t8 T8) Func7[T1, T2, T3, T4, T5, T6, T7, R] {
	return Partial8R(fn, t8)
}

func Partial8[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t1 T1) Func7[T2, T3, T4, T5, T6, T7, T8, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N1[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t1 T1) Func7[T2, T3, T4, T5, T6, T7, T8, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N2[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t2 T2) Func7[T1, T3, T4, T5, T6, T7, T8, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N3[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t3 T3) Func7[T1, T2, T4, T5, T6, T7, T8, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N4[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t4 T4) Func7[T1, T2, T3, T5, T6, T7, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N5[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t5 T5) Func7[T1, T2, T3, T4, T6, T7, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N6[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t6 T6) Func7[T1, T2, T3, T4, T5, T7, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N7[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t7 T7) Func7[T1, T2, T3, T4, T5, T6, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8N8[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t8 T8) Func7[T1, T2, T3, T4, T5, T6, T7, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

func Partial8R[
	T1, T2, T3, T4, T5, T6, T7, T8, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8) R,
](fn F, t8 T8) Func7[T1, T2, T3, T4, T5, T6, T7, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8)
	}
}

type Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R any] func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R

func Of9[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R](fn)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
	return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial(t1 T1) Func8[T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return Partial9(fn, t1)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial1(t1 T1) Func8[T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return Partial9N1(fn, t1)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial2(t2 T2) Func8[T1, T3, T4, T5, T6, T7, T8, T9, R] {
	return Partial9N2(fn, t2)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial3(t3 T3) Func8[T1, T2, T4, T5, T6, T7, T8, T9, R] {
	return Partial9N3(fn, t3)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial4(t4 T4) Func8[T1, T2, T3, T5, T6, T7, T8, T9, R] {
	return Partial9N4(fn, t4)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial5(t5 T5) Func8[T1, T2, T3, T4, T6, T7, T8, T9, R] {
	return Partial9N5(fn, t5)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial6(t6 T6) Func8[T1, T2, T3, T4, T5, T7, T8, T9, R] {
	return Partial9N6(fn, t6)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial7(t7 T7) Func8[T1, T2, T3, T4, T5, T6, T8, T9, R] {
	return Partial9N7(fn, t7)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial8(t8 T8) Func8[T1, T2, T3, T4, T5, T6, T7, T9, R] {
	return Partial9N8(fn, t8)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) Partial9(t9 T9) Func8[T1, T2, T3, T4, T5, T6, T7, T8, R] {
	return Partial9N9(fn, t9)
}

func (fn Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R]) PartialR(t9 T9) Func8[T1, T2, T3, T4, T5, T6, T7, T8, R] {
	return Partial9R(fn, t9)
}

func Partial9[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t1 T1) Func8[T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N1[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t1 T1) Func8[T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N2[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t2 T2) Func8[T1, T3, T4, T5, T6, T7, T8, T9, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N3[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t3 T3) Func8[T1, T2, T4, T5, T6, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N4[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t4 T4) Func8[T1, T2, T3, T5, T6, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N5[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t5 T5) Func8[T1, T2, T3, T4, T6, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N6[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t6 T6) Func8[T1, T2, T3, T4, T5, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N7[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t7 T7) Func8[T1, T2, T3, T4, T5, T6, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N8[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t8 T8) Func8[T1, T2, T3, T4, T5, T6, T7, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9N9[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t9 T9) Func8[T1, T2, T3, T4, T5, T6, T7, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

func Partial9R[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) R,
](fn F, t9 T9) Func8[T1, T2, T3, T4, T5, T6, T7, T8, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9)
	}
}

type Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any] func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R

func Of10[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F) Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R](fn)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Call(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
	return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial(t1 T1) Func9[T2, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return Partial10(fn, t1)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial1(t1 T1) Func9[T2, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return Partial10N1(fn, t1)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial2(t2 T2) Func9[T1, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return Partial10N2(fn, t2)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial3(t3 T3) Func9[T1, T2, T4, T5, T6, T7, T8, T9, T10, R] {
	return Partial10N3(fn, t3)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial4(t4 T4) Func9[T1, T2, T3, T5, T6, T7, T8, T9, T10, R] {
	return Partial10N4(fn, t4)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial5(t5 T5) Func9[T1, T2, T3, T4, T6, T7, T8, T9, T10, R] {
	return Partial10N5(fn, t5)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial6(t6 T6) Func9[T1, T2, T3, T4, T5, T7, T8, T9, T10, R] {
	return Partial10N6(fn, t6)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial7(t7 T7) Func9[T1, T2, T3, T4, T5, T6, T8, T9, T10, R] {
	return Partial10N7(fn, t7)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial8(t8 T8) Func9[T1, T2, T3, T4, T5, T6, T7, T9, T10, R] {
	return Partial10N8(fn, t8)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial9(t9 T9) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T10, R] {
	return Partial10N9(fn, t9)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) Partial10(t10 T10) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return Partial10N10(fn, t10)
}

func (fn Func10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R]) PartialR(t10 T10) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return Partial10R(fn, t10)
}

func Partial10[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t1 T1) Func9[T2, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N1[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t1 T1) Func9[T2, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return func(t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N2[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t2 T2) Func9[T1, T3, T4, T5, T6, T7, T8, T9, T10, R] {
	return func(t1 T1, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N3[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t3 T3) Func9[T1, T2, T4, T5, T6, T7, T8, T9, T10, R] {
	return func(t1 T1, t2 T2, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N4[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t4 T4) Func9[T1, T2, T3, T5, T6, T7, T8, T9, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N5[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t5 T5) Func9[T1, T2, T3, T4, T6, T7, T8, T9, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t6 T6, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N6[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t6 T6) Func9[T1, T2, T3, T4, T5, T7, T8, T9, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t7 T7, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N7[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t7 T7) Func9[T1, T2, T3, T4, T5, T6, T8, T9, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t8 T8, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N8[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t8 T8) Func9[T1, T2, T3, T4, T5, T6, T7, T9, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t9 T9, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N9[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t9 T9) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T10, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t10 T10) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10N10[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t10 T10) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}

func Partial10R[
	T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any,
	F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) R,
](fn F, t10 T10) Func9[T1, T2, T3, T4, T5, T6, T7, T8, T9, R] {
	return func(t1 T1, t2 T2, t3 T3, t4 T4, t5 T5, t6 T6, t7 T7, t8 T8, t9 T9) R {
		return fn(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)
	}
}
